name: FirstWorkFlow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Chose Environment
        default: "staging"
        required: true
        type: choice
        options:
         - staging
          - production
       
 
jobs:
    example-job:
      runs-on: ubuntu-latest

      steps:
        - name: print a welcome message
          run: echo "welocome to firstWorkFlow ${{inputs.environment}}"
